### ISSUE TITLE
Points not adjusting size

### ISSUE THREAD

**Issue by roaldarbol** [burghoff/Scientific-Inkscape#4]
Hi again, sorry to pile on. Please address these at your own pace. :-)

It seems that the Scaling doesn't work well with markers such as points. Here's a simple raw example:
![Screenshot 2022-12-15 at 11 32 16](https://user-images.githubusercontent.com/25629697/207850202-44c01128-a1de-4f41-9eaa-479a40c4944c.png)

And here's the scaled version of it, tried both with Scaling mode and Correction mode:
![Screenshot 2022-12-15 at 11 34 21](https://user-images.githubusercontent.com/25629697/207850256-b98267e9-97c2-4896-8eef-e482d47f62c4.png)

There also seems to be something funky happening with the header, but I think that's simply because it's not rendered well in the original (I can create a separate issue if you'd like me to dig into it a bit).

**Comment by burghoff** [comment]
That's actually not an issue, that's the intended behavior. Markers are just paths in SVGs, so there's no real difference between them and the rest of your plot (which is supposed to be scaled). What you can do is mark them as Unscaled manually, using the Advanced tab. They'll remain as they are during the scaling.

The text looks clipped for some reason. You can remove it manually using Object > Clip > Release Clip.

**Comment by roaldarbol** [comment]
Ah I see. So that means you can't get them round with Correction mode I take it? And I guess it means it's more time-efficient to output SVGs with correct dimensions rather than specifying all the exceptions (e.g. in a point plot).

Re the text, yes there's some clipping, but actually I found out that `Split distant text and lines` breaks them apart after the dash - is that intended behaviour?

**Comment by burghoff** [comment]
No, it should still work in Correction Mode. Just enter the group, select them, and mark them.

When it comes to markers, you can usually select them in bulk, unselect anything anything that's supposed to scale, and then mark them as Unscaled. That speeds things up. But yes, generating things correct from the start is always best.

I believe that the splitting is intended. It's splitting it because it's interpreting it as "0.5" and "-1", because it thinks they might be closely-spaced ticks on an x-axis. The text stuff is a whole zoo of thresholds and rules of thumb, so it's not perfect. In that case, I would undo the scaling and group the two text items together, which will keep them from separating.
